services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  mysqlUsers:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=userDatabase'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=secretPassword'
      - 'MYSQL_USER=thisUser'
    ports:
      - '3306'
volumes:
  mysql:
  mysqlUsers:
